### ISSUE TITLE
UI test setup

### ISSUE THREAD

**Issue by S-Panta** [owncloud/moodle-repository_ocis#17]
Set up UI test in Moodle that uses oCIS as the repository.
- [x] Setup PlayWright for running tests locally. https://github.com/owncloud/moodle-repository_ocis/pull/14
- [x] Setup test in CI. 

One of the preconditions of the test is to make sure your Moodle gets access to oCIS. After Oauth2 access is granted, one has to log in to the oCIS once when they select oCIS for upload and choose `allow` when it asks for permission to read files from oCIS.  Note: This process should be done only once.

**Comment by PhMemmel** [comment]
Like described in #24 I very much recommend to use the moodle behat framework. Everything is already prepared including pipeline setup etc., one just has to write the feature files including the scenarios. The pipeline will spawn up a complete blank and preconfigured moodle instance, you can then configure the settings for your UI test directly in the feature file. See https://moodledev.io/general/development/tools/behat

**Comment by S-Panta** [comment]
Should the steps in feature file be written like [this](https://github.com/owncloud/moodle-repository_ocis/blob/033fc39dd0050ae8fd3f66b6f3c34687123a5cde/tests/behat/uploadFileToMoodle.feature#L22C4-L22C23)? These steps can be found in many feature files that are inside moodled. I suggest we write these things clearly and inside step definition we call the function that this steps is calling?  
For example we can write `When I click on Personal drive` instead of ` When I click on "//*[@class='fp-filename-field']/p[text()='Personal']" "xpath_element"`
@individual-it  @amrita-shrestha  @phil-davis  @nirajacharya2

**Comment by individual-it** [comment]
I think I would prefer to have the xpath hidden in the php function (inside a page object) and not written out in the feature file

**Comment by phil-davis** [comment]
> I think I would prefer to have the xpath hidden in the php function (inside a page object) and not written out in the feature file

I agree.

Do "the moodle people" allow us to create our own step definitions with human-friendly words?
Or do we have to use the steps-for-technical-nerds that moodle already has?

**Comment by individual-it** [comment]
I think for our own steps we can do whatever we want, but should be still consistent with the moodle way.
I just feel having the xpath in the step definition will get us into trouble

**Comment by S-Panta** [comment]
This issue can be closed as the UI test for moodle is completed.
