### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by PhMemmel** [owncloud/moodle-repository_ocis#24]
For automatic checking of moodle specific requirements (unit testing, moodle code style, ...) it is recommended to enable GitHub Actions for the plugin repository.

https://moodlehq.github.io/moodle-plugin-ci/#github-actions

**Comment by micbar** [comment]
There are more than one ways to reach the goal 😄 

We are using DroneCI

**Comment by individual-it** [comment]
Yes, following the `Using in a Local Dev Environment` we should be able to run it in drone.
BTW, `phpcbf` checks already run in CI here

**Comment by PhMemmel** [comment]
I agree in general that there are more ways to reach a goal. But sometimes one specific way has advantages over others ;-)

But fun aside. I'm not used to DroneCI, but from what I see in the config file you only set up some codestyle checking. However, if you have a look at the link I provided you will see that via GHA moodle provides a moodle specific tool (moodle-plugin-ci) including a whole set of different checks ensuring the plugin works in a moodle environment.

It not only includes moodle specific codestyle (which you did via drone which as such is ok), but also includes various typical moodle checks, runs the phpunit tests and behat tests in the correctly set up moodle environment, will keep in sync with changes in the moodle code style, runs the jobs against configured moodle versions to ensure the plugin is compatible with all supported moodle versions, runs grunt jobs for ensuring codestyle on CSS and JS (even if not used in this plugin yet) and so on. So I really recommend thinking about enabling GHA and the moodle specific CI. It's as easy as copying and maybe slightly adapting the example config file: https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml

If you want to stick to droneCI I recommend to use the moodle-plugin-ci and add a similar pipeline to this plugin. And of course it would be nice to link the droneCI to the github repository, so every PR instantly can be checked.

**Comment by amrita-shrestha** [comment]
@individual-it i think drone ci is enough no need to enable github-action should we close this issue

**Comment by PhMemmel** [comment]
As far as I can see from the configuration in this repository, currently drone only runs behat and code style checks. If you really want to stick to only use drone I suggest to implement all the checks moodle-plugin-ci is providing (which is far more than just code style checking). Also AFAIK this plugin is supposed to be published in the moodle plugins directory. Usually using GHA with moodle-plugin-ci is recommended, especially because external contributors will also have access to the results of the pipeline results. Using the moodle-plugin-ci will also make sure this project automatically keeps up with latest changes to moodle coding standards.

**Comment by phil-davis** [comment]
This is an open repo, so the drone results are public. But also GitrHub actions logs will also be public.
If some simple things like moodle code style... checks are in GitHub actions, that will not take up much of whatever free allowance GutHub gives for public repos CI.

So maybe it is a good idea to implement GitHub actions for moodle-specific CI thagt already has a Moodle-GitHub-action workflow that is well-known. It will be easy to implement, and easy to keep up-to-date.

@micbar you commented a while ago "We are using DroneCI" - is a mixed GHA plus drone CI solution OK?

**Comment by danmarsden** [comment]
I think it would be pretty useful for you to at least trial this to see all the errors that our standard tests throw on your codebase. 

keep in mind that github actions are free for public repos - they are rate-limited to prevent your "owncloud" main repo from burning through a lot of time - so if you are using github actions in a lot of other repos and you are making a lot of changes/commits to this repo (and others that rely on github actions) you might find them runnnig a little slower, but we have heaps of repos on my main org with a lot of github action usage and I don't typically notice the rate limiting very often.
https://github.com/orgs/catalyst/repositories

**Comment by danmarsden** [comment]
the short detail on how to set this up if you want to trial it - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

**Comment by individual-it** [comment]
I think its rather the effort to maintain two different CI systems

**Comment by danmarsden** [comment]
it's pretty low impact on effort tbh - the main effort is in modifying the github action config to tell it which moodle branches you want to run it on - you can also use github actions to auto-deploy code to moodle.org plugins db (decreasing the effort maintaining the plugins db code.)

At Catalyst - we use a reusable workflow approach - which we make available for anyone to use and makes it easier for us to maintain across all our moodle plugin repos but I usually reccomend people look at the official "moodle" option first.... but in case it's useful - here's an example workflow that once it lands - doesn't usually need any further changes...
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_403_STABLE/.github/workflows/ci.yml

although one day - Moodle HQ might pull that into their main repo.

docs on that template here:
https://github.com/catalyst/catalyst-moodle-workflows?tab=readme-ov-file#reusable-workflows

but basically - it relies on you having this sort of line in your version.php:
$plugin->supported = [35, 402];

then the github actions will just run the workflows for whatever versions you have defined your plugin supports - and if you grab a moodle.org secret, store it in your github actions store, then when you bump the version in the version.php file if tests all pass it will deploy the updated code to the plugins db as well.

**Comment by micbar** [comment]
I want to unblock this.

Let me be elaborate my POV:

You are argumenting that GiHub actions are "shared" knowledge regarding this plugin, i would accept that.

**Comment by danmarsden** [comment]
note - this is NOT a blocker for plugins db approval - just very handy to have for various reasons :-) - and also has the potential to allow you to auto-publish new versions of your plugin to the moodle.org plugins database with little effort.

**Comment by micbar** [comment]
enabled gh actions for this repo.

**Comment by individual-it** [comment]
the checks will be enabled with #102
