### ISSUE TITLE
Privacy Provider is missing

### ISSUE THREAD

**Issue by tholudwig** [owncloud/moodle-repository_ocis#25]
A Moodle plugin must comply with the European General Data Protection Regulation (GDPR). Moodle has its own corresponding API for this, which must be supported in every plugin.

You can find out more about this topic at: https://moodledev.io/docs/apis/subsystems/privacy

The use of a simple NULL provider must be checked, provided that no user data (userid, userprefrences,...) or similar is stored by the plugin.

**Comment by individual-it** [comment]
## What other repositories do:
- Google Docs stored data: 'email' , 'searchtext'
- Dropbox stored data: (search)'query'
- Nextcloud: null provider

## Our situation:
- We don't have (yet) a search functionality and don't require the user to enter any data. The user only enters data in ocis, but not in the plugin.
- No userpreferences can be set in the plugin.
- The plugin has access to some data e.g. the token contains user-data and the plugin knows which file was selected, but it does not store or remember this data.
- The plugin sends the token to ocis to do WebDAV or Webfinger requests, but these are information ocis already has and nothing the user has entered.

## Conclusion:
Looking at what others do and what the abilities of this plugin is, in my opinion we can implement the NULL provider.

@tholudwig @dj4oC Is my observation and conclusion correct?

**Comment by PhMemmel** [comment]
From my point of view and according to the situation you described a null provider is sufficient.

Regarding the storing of token: This plugin uses the moodle oauth api for that, so to be precise not the plugin itself sends/stores data, but the moodle core oauth component should already deal with the privacy API regarding the storing of tokens etc.

**Comment by dj4oC** [comment]
Agree
