### ISSUE TITLE
Licence header in every file

### ISSUE THREAD

**Issue by individual-it** [owncloud/moodle-repository_ocis#31]
Other plugins start the license header with
`// This file is part of Moodle - https://moodle.org/`

So far in this repo I've been using
`// This file is part of the ocis repository for Moodle - http://moodle.org/`

What do we want to do in future?

CC @PhMemmel @phil-davis @dj4oC

**Comment by dj4oC** [comment]
I suppose we're going to maintain this repo mostly do I would love to read our name in it: is part of the ownCloud Infinite Scale for moodle Repository with the contribution of Staatsinstitut für Schulqualität und Bildungsforschung, JankariTech and ownCloud - a kiteworks company.

**Comment by PhMemmel** [comment]
Looks like it's ok to adapt the basic comment, see:

https://github.com/maths/moodle-qtype_stack/blob/master/question.php

**Comment by individual-it** [comment]
moodle style is strict about the length of the lines and the content of the third line, that's why here a proposal how to solve it: #52 
I've placed the contributors at the bottom of the comment block.
