### ISSUE TITLE
copyright mentions

### ISSUE THREAD

**Issue by individual-it** [owncloud/moodle-repository_ocis#32]
When developing this plugin I've copied a lot of files [from an other plugin](https://github.com/moodle/moodle/blob/main/repository/nextcloud/) and modified them. So I've given credit to whoever was in the `@copyright` header by leaving it and adding `Owncloud`
e.g.

```
/**
 * oCIS repository plugin library.
 *
 * @package    repository_ocis
 * @copyright  2017 Project seminar (Learnweb, University of Münster)
 * @copyright  2023 ownCloud GmbH
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or
 */
```

If a function / class was not changed I've haven't changed the `@copyright` line

Is that the correct way to handle the GPL3 license or what do we want to do in future?

CC @PhMemmel @phil-davis @dj4oC

**Comment by dj4oC** [comment]
@hodyroff can you help please?

**Comment by individual-it** [comment]
@hodyroff ping

**Comment by hodyroff** [comment]
Yes, this is the proper way.

**Comment by hodyroff** [comment]
Will we provide this upstream, or will this live in this repo for the time beeing?

**Comment by individual-it** [comment]
@hodyroff this will be living in this repo forever, no contribution to upstream because this is not extending the upstream project, but a complete own project.
The "upstream" project was only taken as a launchpad to be able to start quicker and so some files have been copied over and got adapted.
