### ISSUE TITLE
Feature Request: Open auth flow for different users

### ISSUE THREAD

**Issue by PhMemmel** [owncloud/moodle-repository_ocis#38]
I am not sure, if this can be implemented at all, but here is the use case:

- A user has 2 accounts teacher1 and teacher2 at an external OIDC IDP.
- The user logs into moodle with account teacher1
- teacher1 wants to add a file from ocis, opens the repository and triggers the login there
- teacher1 will be redirected to the ocis instance where the teacher1 will be immediately logged in without user interaction, because teacher1 still has the valid session of the external OIDC IDP which is a great feature to have
- teacher1 now wants to access files from its other account teacher2, so he logs out of repository, and tries to log in again with teacher2 account. However, there still is the teacher1 session of the external OIDC IDP, so the user will immediately log in as teacher1 again. There is no chance for the user to log in with a different account.

What would be great:
- First login will be automatically done with the same account the user is currently logged in into moodle via the external OIDC IDP
- After loggin out in the repository it would be awesome if the user would be able to open up a separate session with a different account, so he can retrieve files from ocis via account teacher2 and still be logged in as teacher1 in moodle.

Is this possible to achieve somehow?

**Comment by michaelstingl** [comment]
Known limitation with Keycloak setups. Other IdP respect the `prompt=select_account` parameter.

Related:
- https://github.com/owncloud/enterprise/issues/5678
- Screenshots: https://github.com/owncloud/docs-server/issues/938#issuecomment-1508523827
  (comparison Keycloak vs built-in IdP) 
- Problem in iOS app: https://github.com/owncloud/ios-app/issues/1199

/cc @wkloucek

**Comment by micbar** [comment]
@michaelstingl thanks for sharing the information.

**Comment by individual-it** [comment]
Closing this for now as it seems not to be possible with your Keycloak, we can open it again if the situation changes
