### ISSUE TITLE
Error message to User must be in proper format

### ISSUE THREAD

**Issue by S-Panta** [owncloud/moodle-repository_ocis#39]
When the folder inside any directory ( Personal, Shares or Spaces) are deleted and somehow your filepicker is at that current folder, it will throw an exception. I suppose we could show proper message rather than the error exception thrown. 
![Screenshot from 2023-12-11 10-13-35](https://github.com/owncloud/moodle-repository_ocis/assets/64484313/1e7f8863-f1f6-491e-b4a2-2a7cb047e30b)

**Comment by phil-davis** [comment]
The folder has probably been deleted in ocis by some other client.
Maybe say "Folder no longer exists"
But then what to do? Automagically navigate the UI up to the parent folder (if that exists), or up each level to the first thing that exists? (might be the root of the available ocis storage)

**Comment by individual-it** [comment]
It looks like in moodle one has to throw an special exception and the error popup will be created from that.
If a general exception is thrown and debugging is enabled the error message looks like the one in this issue.

Proposal to fix it with better human readable error messages in #40
