### ISSUE TITLE
Use web UI icons as default for Personal, Shares, Spaces

### ISSUE THREAD

**Issue by PhMemmel** [owncloud/moodle-repository_ocis#75]
Follow-up for #54

To make the UX as consistent as possible it would be nice to add the icons from the web UI to the repository and make the config options created in #54 point to them as default:

![grafik](https://github.com/owncloud/moodle-repository_ocis/assets/65113153/feda4990-b79e-45cc-a1cb-89f3fe87ced2)

**Comment by individual-it** [comment]
proposed fix in #76
