### ISSUE TITLE
FilePicker doesn't get synced when the drive display is changed to `No` 

### ISSUE THREAD

**Issue by S-Panta** [owncloud/moodle-repository_ocis#86]
When disabling `show drive` setting of Personal drive ( or project drive)  on ocis plugin and if the file picker is on the same drive and if no reload is clicked, it works normally. On clicking reload, the drive is not shown ( which is the expected behavior) 

1. Create a folder in Ocis and select personal drive display as `yes`. 
2. Open the New Tab and select display for Personal Drive to `no`.
3. Create another folder inside the Personal drive.
4. That Folder is accessible from Filepicker as long as it isn't reloaded. 

[Screencast from 02-27-2024 04:01:38 PM.webm](https://github.com/owncloud/moodle-repository_ocis/assets/64484313/fe1ae549-1716-4a73-afab-bf63236bb580)

**Comment by individual-it** [comment]
I think this is not a problem, the data is accessible by the API, but just not listed in the UI. That is the same in the ocis-web-UI
