### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by purnendudash** [owncloud/moodle-repository_ocis#96]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin uses user data which will need to be included in the privacy api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy#

**Comment by purnendudash** [comment]
Sorry, my wrong. I skipped that somehow. Its already there.

**Comment by individual-it** [comment]
yes it's here https://github.com/owncloud/moodle-repository_ocis/blob/main/classes/privacy/provider.php
AFAIK: its similar to other plugins that connect cloud storages to moodle
