### ISSUE TITLE
should env. variables follow frankenstyle naming rules?

### ISSUE THREAD

**Issue by individual-it** [owncloud/moodle-repository_ocis#99]
This repository uses following env. variables for auto-provisioning:

- MOODLE_DISABLE_CURL_SECURITY
- MOODLE_OCIS_URL
- MOODLE_OCIS_CLIENT_ID
- MOODLE_OCIS_CLIENT_SECRET
- MOODLE_OCIS_LOGO_URL

The [discussion](https://github.com/owncloud/moodle-repository_ocis/issues/94#issuecomment-2044412725) is, if there are supposed to be changed to frankenstyle.

@danmarsden please add your opinion, happy to change it, if its a requirement

**Comment by danmarsden** [comment]
I can't actually find a policy related to environment vars anywhere in the dev docs - the majority of those have OCIS in them so I'd just ignore them and walk away, the MOODLE_DISABLE_CURL_SECURITY one is a bit problematic in it's naming... but I'm hoping you'll dump that from use anyway....
